### ISSUE TITLE
Add Twitch PubSub service

### ISSUE THREAD

**Issue by daniel0611** [codeoverflow-org/nodecg-io#116]
### Description
We should add a Twitch PubSub service to be able to react to e.g. channel points. Full list of supported events: https://dev.twitch.tv/docs/pubsub#topics. As a package we should use [twitch-pubsub-client](https://www.npmjs.com/package/twitch-pubsub-client).
I think the currently existing nodecg-io-twitch service should be renamed with this change to nodecg-io-twitch-chat inorder to make it clear that it only handles the chat and not other parts of Twitch.

**Comment by derNiklaas** [comment]
Twitch PubSub is just using a websocket-client, so i dont think this is a major thing

**Comment by daniel0611** [comment]
Agreed, but it would be still be nice to have this at some point so authentication can be done by the framework

**Comment by derNiklaas** [comment]
I just experimented with the package mentioned above. Looks easy to work with. 
[Small gist with example of the package](https://gist.github.com/derNiklaas/de523310ad74b6b0cf8b12bd23a35d76)
I'll try to finish it until thursday so @sebinside can use it on friday.
