### ISSUE TITLE
Harmonize service abstraction level

### ISSUE THREAD

**Issue by NeoCortex97** [codeoverflow-org/nodecg-io#124]
### Description
Make the services consistent and add abstraction funcions, where they are not present atm.
The following services do not provide abstraction:

- [ ] nodecg-io-discord
- [ ] nodecg-io-midi-input
- [ ] nodecg-io-midi-output
- [ ] nodecg-io-obs
- [ ] nodecg-io-philipshue
- [x] nodecg-io-sacn-receiver
- [x] nodecg-io-sacn-sender
- [ ] nodecg-io-slack
- [ ] nodecg-io-spotify
- [ ] nodecg-io-streamdeck
- [ ] nodecg-io-telegram
- [ ] nodecg-io-twitch
- [ ] nodecg-io-twitter
- [ ] nodecg-io-websocket-server

**Comment by StefanSchmelz** [comment]
Realized that the sACN-sender has at least some abstraction

**Comment by StefanSchmelz** [comment]
Checked the sACN receiver and found abstractions too.

**Comment by StefanSchmelz** [comment]
Hope i caught every service, where i missed abstractions

**Comment by daniel0611** [comment]
Closed by #184/#91, when we find a service where a meaningul simplifictation can be added we can add them.
