### ISSUE TITLE
Atem service

### ISSUE THREAD

**Issue by NeoCortex97** [codeoverflow-org/nodecg-io#139]
### Description
Since devices like Blackmagic Designs Atem mini are rather popular. I think we should support Blackmagic Designs open protocol to control the atem devices.

**Comment by NeoCortex97** [comment]
Here is a library to interface with atem:
https://www.npmjs.com/package/atem-connection

**Comment by chron0** [comment]
I've seen countless OBS switching integrations but not a single one for ATEM and it would really be great.
