### ISSUE TITLE
Use a interface to enforce our native client requirement

### ISSUE THREAD

**Issue by daniel0611** [codeoverflow-org/nodecg-io#15]
### Description
We should use a interface that all service clients need to implement. This should contain a function named `getNativeClient()` that returns the original client. This way we enforce our requirement that all services need to provide access to the underlying client and we also enforce this exact name.

If we decide to add other functions that should also be available on all clients we can also add them to this interface.

Enhancement idea by @sebinside on stream and on discord.

**Comment by sebinside** [comment]
Results of recent discussion: The interface shall be implemented by the services clients and not extended by a new interface for which an object is created afterwards (like in apperently most of the current implementations). This practise violates the DRY principle.
