### ISSUE TITLE
Add service instance name to logs of services

### ISSUE THREAD

**Issue by daniel0611** [codeoverflow-org/nodecg-io#155]
### Description
Currently all log messages from services don't indicate of which service instance they stem.
This can become a problem if you have more than one instance of a service type and a sudden log appears and you don't know which instance is producing it.

To address this `ServiceBundle` should provide logging methods which prepend the current instance name in front of all messages.

**Comment by Kieferleiter** [comment]
@daniel0611 are you already working on this? Or can I give it a try?

**Comment by daniel0611** [comment]
No, I haved looked in this yet. Sure go ahead and give it a try.
