### ISSUE TITLE
nodecg-io-streamelements doesn't connect to the API

### ISSUE THREAD

**Issue by derNiklaas** [codeoverflow-org/nodecg-io#171]
### Description
StreamElements doesn't work because of connection issues.

### How to reproduce
Setup a bundle that uses StreamElements (for example: StreamElements-events).
Setup a StreamElements instance.
Check for a "start" message. (streamelements-event: "SE client has been updated, registering handlers now.")

### Error Log 
After adding some debug messages, I've got the following error: 
onConnectionError: _timeout_

**Comment by daniel0611** [comment]
Closing this as it seems to be working for you now as you've created #287.

**Comment by derNiklaas** [comment]
I forgot this issue even existed. Sorry 😅
