### ISSUE TITLE
RCON Server not being online lets nodecg crash

### ISSUE THREAD

**Issue by daniel0611** [codeoverflow-org/nodecg-io#19]
### Description
When a RCON instance exists and the server can't be reached the RCON service lets NodeCG crash because of an exception even though there is a try catch block in the `createClient` function of the RCON Service:
https://github.com/codeoverflow-org/nodecg-io/blob/413d0dfaa34d9bcbf63c4c91c9ecf3a98c00b7ab/nodecg-io-rcon/extension/index.ts#L55-L71

### How to reproduce
1. Create a RCON Service instance while the corresponding server is running.
2. Exit NodeCG and (in my case) stop the server.
3. Run NodeCG and try to login, the error will be logged.

### Error Log 
```
UNCAUGHT EXCEPTION! NodeCG will now exit.
{ Error: connect ECONNREFUSED 127.0.0.1:25575
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 25575 }
```

### References
RCON PR: #16

**Comment by derNiklaas** [comment]
This also occurs when using a websocket-client tries to connect to a server.
