### ISSUE TITLE
Stop all service clients when NodeCG is stopping

### ISSUE THREAD

**Issue by daniel0611** [codeoverflow-org/nodecg-io#21]
### Description
Currently service clients just get killed when stopping NodeCG.
Instead all clients should be gracefully stopped when NodeCG is stopping by using the `stopClient` function of the corresponding services.

**Comment by Tim-Tech-Dev** [comment]
@noeppi-noeppi Is this issue definitely fixed? - If so could you remove it from the Streamdeck-sample docs? Thanks

https://github.com/codeoverflow-org/nodecg-io-docs/blob/debb00cb5296fb8e4ed8c5340faead4172c75117/docs/samples/streamdeck.md#L34
