### ISSUE TITLE
Reduce boilerplate of service implementation

### ISSUE THREAD

**Issue by daniel0611** [codeoverflow-org/nodecg-io#22]
### Description
There currently exists way too much boilerplate in the client implementation. 
To do this the implementation should be moved into a class which extends a class provided by the framework. This base class could do things like getting the core using a nodecg instance and printing a log if it is not loaded.

**Comment by Tim-Tech-Dev** [comment]
When we move
```Typescript
if (core === undefined) {
        nodecg.log.error("nodecg-io-core isn't loaded! Discord bundle won't function without it.");
        return undefined;
}
```
into the framework,  when will it report that there is no framework?

**Comment by daniel0611** [comment]
We can export the base class and import it in the service bundle just as a normal node dependency as they get linked for typings anyway. The constructor of that class can then do this call by using the nodecg instance that it gets passed by the service bundle. I have not tested it yet but to my understanding this should work.

**Comment by Tim-Tech-Dev** [comment]
Yes, it does indeed work (tested in  my branch [enhancement/service-boilerplate](https://github.com/Tim-Tech-Dev/nodecg-io/tree/enhancement/service-boilerplate)). But why should we report that there is no framework when the code witch would report that is in the framework itself?

**Comment by daniel0611** [comment]
That the node library is available is ensured by npm, but that the nodecg bundle has been loaded is a different story, we can't ensure that. People might forget to put it in or it might have crashed at startup, in which case nodecg just proceeds with loading the next bundles, meaning the service bundles. Thus we should still check that it has been loaded just as a safety measure.

**Comment by Tim-Tech-Dev** [comment]
ok, I will add the check back.
