### ISSUE TITLE
Add sql service

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/nodecg-io#223]
### Description
Add service to connect to mysql databases. There are multiple commonly used npm packages available.

### References
https://www.npmjs.com/package/knex

**Comment by promasu** [comment]
We should add a general service for SQL and use adapters for the specific implementations like sqlite, pgsql, mysql

**Comment by LarsVomMars** [comment]
In this case we should also consider NoSQL databases like Mongo and Redis.

Otherwise, I would recommend using the [mariadb](https://www.npmjs.com/package/mariadb) package for mysql connection due to its performance benefits.

**Comment by promasu** [comment]
NoSQL Databases are a bit out of scope aren't they?
