### ISSUE TITLE
telegram-bot-api: Automatic enabling of cancellation of promises is deprecated

### ISSUE THREAD

**Issue by Tim-Tech-Dev** [codeoverflow-org/nodecg-io#267]
While starting `NodeCG`, I get a deprecation warning.

### Error Log 

node-telegram-bot-api **deprecated** Automatic enabling of cancellation of promises is deprecated.  
In the future, you will have to enable it yourself.  
See <https://github.com/yagop/node-telegram-bot-api/issues/319>. node:internal/modules/cjs/loader:1101:14

### References

https://github.com/yagop/node-telegram-bot-api/issues/319#issuecomment-324963294

**Comment by cimerio7** [comment]
I am getting the same error
