### ISSUE TITLE
twurple:pubsub ERROR Disconnected unexpectedly: [1006] spams in console.

### ISSUE THREAD

**Issue by SteffoSpieler** [codeoverflow-org/nodecg-io#295]
### Description
Every minute there's an error in the console.

### How to reproduce

- Install nodecg-io.
- Create and setup a pubsub client.
- See result.

### Error Log 
 
![](https://cdn.discordapp.com/attachments/577495348898168832/906511851339255818/unknown.png)

**Comment by daniel0611** [comment]
Are you still experiencing this problem with the latest version?

**Comment by SteffoSpieler** [comment]
no

**Comment by daniel0611** [comment]
I'll close this issue then. If you encounter this problem again, please don't hesitate to reopen this issue.
