### ISSUE TITLE
Add support for unattended install with nodecg-io-cli

### ISSUE THREAD

**Issue by ExtremTechniker** [codeoverflow-org/nodecg-io#363]
### Description
Add support for installing without user input e.g. via env variables or with program arguments. 

To use nodecg-io-cli in scripts or in docker images

**Comment by daniel0611** [comment]
This is already implemented in https://github.com/codeoverflow-org/nodecg-io-cli/pull/51.
I'll create a new release once https://github.com/codeoverflow-org/nodecg-io-cli/pull/62 is done.
I'll leave this issue open for now and close it once it has been released and is usable.

**Comment by daniel0611** [comment]
Released with https://github.com/codeoverflow-org/nodecg-io-cli/pull/63
