### ISSUE TITLE
How to contribute link broken

### ISSUE THREAD

**Issue by NastyGamer** [codeoverflow-org/nodecg-io#49]
The How to contribute link (https://github.com/codeoverflow-org/nodecg-io/blob/master/docs/docs/contribute.md) in the readme file is broken and throws an 404 when clicked

**Comment by LarsVomMars** [comment]
Not only this one. The _installation guide_ and the _available services_ link is broken as well - at least in the readme.

**Comment by daniel0611** [comment]
Thanks for finding!
