### ISSUE TITLE
Add OBS service

### ISSUE THREAD

**Issue by daniel0611** [codeoverflow-org/nodecg-io#93]
### Description
There should be a service of OBS using the https://github.com/Palakis/obs-websocket/ plugin.
Potential node.js library https://www.npmjs.com/package/obs-websocket-js

**Comment by derNiklaas** [comment]
What about nodecg-obs?

**Comment by daniel0611** [comment]
With nodecg-io we want to create a streamlined experience for the user and developer. All services are created and managed the same way and also used similarly (once we have not only the underlying clients but also some simplifications on top). Nodecg-obs works completely differently and thus is complicating setup for users and usage for developers.
