### ISSUE TITLE
Usage together with SLOBS api?

### ISSUE THREAD

**Issue by TheGreyDiamond** [codeoverflow-org/nodecg-io#98]
### Description
Please add a way to control items, scene and stuff on slobs based on events. Also please make it possible to listen for events.
(I want to build a "flow", which enables an element as soon as a game capture finds a target)

**Comment by derNiklaas** [comment]
Isn't SLOBS just an edited version of the normal OBS Studio?
You should be able to use the OBS websocket API. 

Also, which Events would you like to listen to?

**Comment by TheGreyDiamond** [comment]
I'm not really sure if that event even exists, but is there an event to listen for a game capture finding a target window?

**Comment by derNiklaas** [comment]
So normal OBS calls work with SLOBS?

**Comment by TheGreyDiamond** [comment]
Can't test it right now, my guess is no, but I will try it tomorrow!

**Comment by sebinside** [comment]
SLOBS is bullshit and violates the idea behind open source software. Just to throw my own two cents in here ✌️

**Comment by TheGreyDiamond** [comment]
Looking into it (I never did, don't judge), you're right. I'm started transitioning to obs (maybe with Streamelements, idk yet), but I will leave this open for people who still want to use SLOBS.
