### ISSUE TITLE
Streamlabs Service

### ISSUE THREAD

**Issue by derNiklaas** [codeoverflow-org/nodecg-io#99]
### Description
Create a simple SLOBS API. 

### References
Request: #98
API document (don't know if it's the current implementation): https://stream-labs.github.io/streamlabs-obs-api-docs/docs/index.html

Edit:
This should be a low priority api. This service is only for a specific subset of OBS Users. 
If the normal OBS Websocket Service works, this will be closed (cause I can't see any differences between the websocket api and Streamlabs own implementation)

**Comment by daniel0611** [comment]
Closing this in favor of #98
